### PR TITLE
Add Russian translation

### PR DESCRIPTION
**Pull request by dragomano**

### CODE REVIEW

**Review by jdarwood007 — APPROVED** [review]
Thank you!

**Comment by jdarwood007** [comment]
@dragomano Are you able to sign your commit?

**Comment by dragomano** [comment]
I think I signed everything, what's wrong?

sshot-12

**Comment by jdarwood007** [comment]
The commit itself wasn't signed, but I will just accept it. Signing your commit with a GPG key is better, as it says it comes from you, and the code you submitted wasn't tampered with.

**Pull request merged**
